###################
# Portfolio Generator by John B. Wyatt IV
# URL: "https://www.github.com/jbwyatt4/portfolio"
# spdx-license: GPL-3.0-or-later
# Loads portfolio.yml
# Projects are listed in the order they are written in portfolio.yml
###################

require 'yaml'

# Load the portfolio and generate/fill the categories
portfolio = YAML.load_file('portfolio.yml')
categories = {}#{'ReactJS':nil, 'Ruby on Rails':nil, 'C/C++':nil}
portfolio['Projects'].each do |p|
  #puts p[1]["groups"].inspect
  p[1]['groups'].each do |g|
    categories[g] = [] if categories[g].nil?
    categories[g].push(p)
  end
end

#p categories.inspect

#p categories.methods.sort

intro_text = %{# John Wyatt's Portfolio

The following is a list of notable projects I have worked on to demonstrate my skills and experience.

You can see my personal website at:

https://jbwyatt4.com

This portfolio might be mirrored on GitHub. For the most up to date version please see the GitLab version:

https://gitlab.com/jbwyatt4/portfolio

This document was auto generated by readme_gen.rb in this portfolio's git repo.
}

footer_text = %{

}

fname = "README.md"
File.open(fname, 'w') { |file|

  # Intro text
  file.write(intro_text)
  file.write("\n")

  # Table of Contents
  file.write("## Table of Contents")
  categories.each do |c|
    file.write("\n\n")
    file.write("[" + c[0] + "](#" + c[0] + ")" )
  end

  # Write out the categories and each of the projects
  categories.each do |c|
    file.write("\n\n")
    #p c.inspect
    file.write("## " + c[0])
    c[1].each do |cc|
      file.write("\n\n")
      file.write(cc[1]["name"])
      file.write("\n\n")
      file.write(cc[1]["desc"])
    end
  end

  # Footer text
  file.write(footer_text)
}

p "README.md generated successfully!"
